title: Nina Polshakova
url: 'https://npolshakova.github.io/'
description: 'I write stuff here.'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

paginate: 10
paginate_path: /page:num/

excerpt_separator: "<!-- break -->"

author: 'Nina Polshakova'
disqus_shortname: npolshakova

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-paginate

sass:
    sass_dir: _sass
    style: :compressed
